"""Shared constants for the KIM HGT converter."""

TARGET_VARIABLE = "hgt"
TARGET_STANDARD_NAME = "geopotential_height"
TARGET_UNIT = "m"
TARGET_LEVEL_HPA = 500.0
EXPECTED_LEVEL_INDEX = 13

VALUE_MIN = 4500.0
VALUE_MAX = 6500.0
ANOMALY_VALUE_MIN = -512.0
ANOMALY_VALUE_MAX = 512.0

SCHEMA_VERSION = 1
ASSET_TYPE = "kim-hgt500-packed-png"
DOMAIN = "glob"

SOURCE_FORECAST_INTERVAL_MINUTES = 180
OUTPUT_FRAME_INTERVAL_MINUTES = 10
INTERPOLATION = "linear"

PACKING = "uint16-rg-big-endian"
PNG_MODE = "RGB"
